apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zpm-registry
  namespace: zpm-registry
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: lets-encrypt-staging
spec:
  rules:
  - host: pm.myardyas.online
    http:
      paths:
      - backend:
          serviceName: zpm-registry
          servicePort: 52773
        path: /(csp)
  tls:
  - hosts:
    - pm.myardyas.online
    secretName: zpm-registry
